
build-runner: ## Executes the flutter pub run build_runner build command, which generates files for the project using the build_runner package.
	@flutter pub run build_runner build --delete-conflicting-outputs

build-runner-watch: ## Runs the flutter pub run build_runner watch command, which watches for changes in the code and automatically triggers the build process.
	@flutter pub run build_runner watch --delete-conflicting-outputs

build-runner-clean: ## Cleans up the build artifacts generated by the build_runner.
	@flutter pub run build_runner clean

fix: ## Applies automatic fixes to the Dart code using the Dart fix command.
	@dart fix --apply
